import Head from 'next/head';
import HeaderComponent from '../components/header/Header.component';
import CardsComponent from '../components/cards/Cards.component';
import content from '../content';
import FooterComponent from '../components/footer/Footer.component';
FooterComponent;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hubble!</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <HeaderComponent />
      <CardsComponent content={content} />
      <FooterComponent />
    </div>
  );
}
